name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu

    steps:
      uses: actions/checkout@v3

      uses: docker/setup-buildx-action@v3

      uses: docker/login-action@v3
      with:
        username: ${}
        password: ${}

      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
